title: Dmitriy Mayboroda
email: mayboroda.de@yandex.ru
description: Trying to find some words for description. No luck.
twitter_username: mayboroda
github_username: mayboroda

markdown: kramdown
permalink: /:year/:title:output_ext